import json
from typing import Any

from pydantic import BaseModel, ValidationError

from app.generation.base import AIGenerator
from app.generation.prompt_builder import build_llm_prompt
from app.generation.providers.base import LLMClient
from app.retrieval.base import KnowledgeResult
from app.schemas.contracts import (
    AIGrounding,
    AIKnowledgeReference,
    AIRequest,
    AIResponse,
)


class LLMGenerationError(ValueError):
    """Raised when an LLM response cannot be converted into AIResponse."""


class LLMExplanation(BaseModel):
    """The portion of AIResponse that is generated by the LLM."""

    summary: str
    reasoning: str
    recommendation: str


class LLMGenerator(AIGenerator):
    """Generate grounded vehicle responses using an LLM provider."""

    def __init__(self, client: LLMClient) -> None:
        self.client = client

    @staticmethod
    def response_schema() -> dict[str, Any]:
        """Return the JSON schema expected from the LLM."""
        return LLMExplanation.model_json_schema()

    def generate(
        self,
        request: AIRequest,
        knowledge: list[KnowledgeResult],
    ) -> AIResponse:
        prompt = build_llm_prompt(
            request,
            knowledge,
        )

        raw_response = self.client.generate(
            prompt,
            response_format=self.response_schema(),
        )

        explanation = self._parse_response(raw_response)

        supporting_evidence_ids = self._select_supporting_evidence(
            request,
        )
        knowledge_references = self._build_knowledge_references(
            knowledge,
        )

        return AIResponse(
            summary=explanation.summary,
            reasoning=explanation.reasoning,
            recommendation=explanation.recommendation,
            supporting_evidence_ids=supporting_evidence_ids,
            knowledge_references=knowledge_references,
            grounding=AIGrounding(
                status=self._determine_grounding_status(
                    evidence_count=len(supporting_evidence_ids),
                    knowledge_count=len(knowledge_references),
                ),
                evidence_count=len(supporting_evidence_ids),
                knowledge_count=len(knowledge_references),
            ),
        )

    @staticmethod
    def _parse_response(raw_response: str) -> LLMExplanation:
        try:
            payload: Any = json.loads(raw_response)
        except json.JSONDecodeError as exc:
            raise LLMGenerationError(
                "LLM response was not valid JSON."
            ) from exc

        if not isinstance(payload, dict):
            raise LLMGenerationError(
                "LLM response must be a JSON object."
            )

        try:
            return LLMExplanation.model_validate(payload)
        except ValidationError as exc:
            raise LLMGenerationError(
                "LLM response did not match the LLM explanation contract."
            ) from exc

    @staticmethod
    def _select_supporting_evidence(
        request: AIRequest,
    ) -> list[str]:
        """Select evidence directly connected to identified risks."""

        priority_risk_ids = set(
            request.decision.priority_risk_ids,
        )

        selected: list[str] = []

        for risk in request.risks:
            if (
                risk.id in priority_risk_ids
                or not priority_risk_ids
            ):
                for evidence_id in risk.evidence_ids:
                    if evidence_id not in selected:
                        selected.append(evidence_id)

        if selected:
            return selected

        return [
            evidence.id
            for evidence in request.evidence
            if evidence.status in {
                "conflicting",
                "partially_verified",
            }
        ]

    @staticmethod
    def _build_knowledge_references(
        knowledge: list[KnowledgeResult],
    ) -> list[AIKnowledgeReference]:
        """Build knowledge references from retrieved documents."""

        return [
            AIKnowledgeReference(
                id=result.document.id,
                title=result.document.title,
                category=result.document.category,
                relevance=result.relevance,
            )
            for result in knowledge
        ]

    @staticmethod
    def _determine_grounding_status(
        *,
        evidence_count: int,
        knowledge_count: int,
    ) -> str:
        if evidence_count > 0 and knowledge_count > 0:
            return "grounded"

        if evidence_count > 0 or knowledge_count > 0:
            return "partially_grounded"

        return "insufficient"